### PR TITLE
Update crossbeam-channel

### PR DESCRIPTION
**Pull request by davidpdrsn**

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Thanks!

**Comment by davidpdrsn** [comment]
@jonhoo any chance you would do a release? I’m trying to get rid of a duplicate dependency in my tree 😊

**Comment by jonhoo** [comment]
@davidpdrsn Yup, give me a second — going to also bump `base64` and `nom`.

**Comment by davidpdrsn** [comment]
Thanks!

**Comment by jonhoo** [comment]
Released as `7.2.0`.

**Pull request merged**
