### PR TITLE
update to nom 4

### PR DESCRIPTION
**Pull request by Geal**
Hello,

I'm currently testing the upgrade to nom 4 on various crates, to see if I forgot anything. There are a few breaking changes, as documented in [the upgrade doc](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md). Apparently, for your crate, there's not much to do, so good news :)
Unfortunately, I have not been able to build the tests yet, the compiler just spins and never stops building them. Maybe it's because I'm on OSX, maybe it's because I didn't wait long enough, we'll see :)

### CODE REVIEW

**Comment by marshallpierce** [comment]
Thanks, I'll take a look!

You're right; the test build does seem to take an extraordinarily long time on macOS... hmmm.

**Comment by jonhoo** [comment]
Looks like Travis is complaining about a test failure:
```
---- serialization::interval_log::tests::duration_fp_roundtrip_accuracy stdout ----
	thread 'serialization::interval_log::tests::duration_fp_roundtrip_accuracy' panicked at 'called `Result::unwrap()` on an `Err` value: Incomplete(Size(1))', /checkout/src/libcore/result.rs:916:5
```

**Comment by marshallpierce** [comment]
I added a bit of debugging output to show what the parse was failing on.

```
---- serialization::interval_log::tests::duration_fp_roundtrip_accuracy stdout ----
	thread 'serialization::interval_log::tests::duration_fp_roundtrip_accuracy' panicked at 'could not parse 1315389239.806: Err(Incomplete(Size(1)))', src/serialization/interval_log/tests.rs:272:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:68
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src/libstd/panicking.rs:391
   3: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   5: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   6: hdrhistogram::serialization::interval_log::tests::duration_fp_roundtrip_accuracy
             at src/serialization/interval_log/tests.rs:272
   7: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1449
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:815
   8: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101
```

Looks like that error would come from `fract_sec_tuple`; any idea why `1315389239.806` is making this mad in nom 4?

```
named!(fract_sec_tuple<&[u8], (u64, &str)>,
    do_parse!(
        secs: flat_map!(recognize!(take_until!(".")), parse_to!(u64)) >>
        tag!(".") >>
        nanos_str: map_res!(take_while1!(is_digit), str::from_utf8) >>
        (secs, nanos_str)
    )
);
```

**Comment by jonhoo** [comment]
I know @ekmartin has also been trying to make this change (https://github.com/HdrHistogram/HdrHistogram_rust/compare/master...ekmartin:nom_4), and apparently he's seeing [this test](https://github.com/HdrHistogram/HdrHistogram_rust/blob/ac7b74ad80263847fe2f7f6ff3aeaf8812c019fc/src/serialization/interval_log/tests.rs#L252-L285) fail with an `Incomplete`. @Geal perhaps you could shine some light here?

**Comment by Geal** [comment]
hello, I fixed the test that was not running. Unfortunately, I added a temporary combinator for that, it was the easiest way to write it. We will probably be able to remove that in nom 4.1.

**Comment by marshallpierce** [comment]
If you say that macro is the right way to get to nom 4, works for me. :) Thanks!

**Pull request merged**
