### PR TITLE
Update CI and make it run

### PR DESCRIPTION
**Pull request by jonhoo**

### CODE REVIEW

**Comment by jonhoo** [comment]
@marshallpierce Looks like there's a legitimate failure on Windows here related to `base64` — do you have any insight into what might be going wrong [here](https://github.com/HdrHistogram/HdrHistogram_rust/runs/4993971046?check_suite_focus=true#step:4:354)? Relevant code:
https://github.com/HdrHistogram/HdrHistogram_rust/blob/c21970820a99a0d27746d1efd547ce6bd34384e4/tests/interval_log.rs#L120-L121

**Comment by marshallpierce** [comment]
Hmm... some shenanigans with windows line endings or something like that perhaps? 

Any recommendations on how to get a useful Windows system for debugging?

**Comment by jonhoo** [comment]
I've had luck with Microsoft's [Windows development environment virtual machines](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) in the past. They're official and free.

**Comment by marshallpierce** [comment]
Ah, I used those in the bad old days when IE compatibility matters. They're 20GB now? wow...

**Pull request merged**
